# Generated by Django 3.1.7 on 2021-03-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('name_ru', models.TextField(null=True, verbose_name='Название')),
                ('name_en', models.TextField(null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Тариф',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('price', models.CharField(blank=True, help_text='$25.00, от $370.00, комиссия х2, Бесплатно, от $35.00 в час, 5.00 %, от $0.30 - до $0.60', max_length=250, null=True, verbose_name='Цена')),
                ('price_ru', models.CharField(blank=True, help_text='$25.00, от $370.00, комиссия х2, Бесплатно, от $35.00 в час, 5.00 %, от $0.30 - до $0.60', max_length=250, null=True, verbose_name='Цена')),
                ('price_en', models.CharField(blank=True, help_text='$25.00, от $370.00, комиссия х2, Бесплатно, от $35.00 в час, 5.00 %, от $0.30 - до $0.60', max_length=250, null=True, verbose_name='Цена')),
                ('cause_time', models.CharField(blank=True, help_text='за коробку, на поддон / мес, по звонку, на единицу', max_length=255, null=True, verbose_name='На кол-во/Время')),
                ('cause_time_ru', models.CharField(blank=True, help_text='за коробку, на поддон / мес, по звонку, на единицу', max_length=255, null=True, verbose_name='На кол-во/Время')),
                ('cause_time_en', models.CharField(blank=True, help_text='за коробку, на поддон / мес, по звонку, на единицу', max_length=255, null=True, verbose_name='На кол-во/Время')),
                ('data_tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_tarifs', to='tarif.datatarif', verbose_name='Тариф')),
            ],
            options={
                'verbose_name_plural': 'Данные Тарифа',
            },
        ),
    ]
