# Generated by Django 3.1.7 on 2021-03-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='image_icon',
            field=models.ImageField(blank=True, help_text='можно взять из сайта  https://www.flaticon.com/', null=True, upload_to='social/', verbose_name='Фото иконка соц.сети'),
        ),
    ]
