# Generated by Django 3.1.7 on 2021-06-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210404_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Отзыв человека')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
