# Generated by Django 3.1.7 on 2021-06-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ФИО')),
                ('number', models.CharField(max_length=21, verbose_name='Номер телефона')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
