# Generated by Django 3.1.7 on 2021-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image_icon', models.ImageField(help_text='можно взять из сайта  https://www.flaticon.com/', upload_to='service/', verbose_name='Фото иконка')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
