# Generated by Django 3.1.7 on 2021-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image', models.ImageField(help_text='можно взять из сайта  https://www.flaticon.com/', upload_to='pay_image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Оплата(фото)',
            },
        ),
    ]
